spring.application.name=booking-ms

spring.datasource.url=jdbc:mysql://localhost:3306/booking_ms?createDatabaseIfNotExist=true
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true

spring.jpa.hibernate.ddl-auto=validate

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.key=${JWT_KEY}

server.port=0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.int}

# OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=false

# Circuitbreak
resilience4j.circuitbreaker.instances.atualizaSala.slidingWindowSize=3
resilience4j.circuitbreaker.instances.atualizaSala.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.atualizaSala.waitDurationInOpenState=50s
resilience4j.circuitbreaker.instances.atualizaSala.registerHealthIndicator=true

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always

# Usar Apache HttpClient 5
spring.cloud.openfeign.httpclient.hc5.enabled=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username= ${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password= ${RABBITMQ_DEFAULT_PASS}

# Tratando falhas no RabbitMQ
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=4
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.listener.simple.retry.multiplier=1
spring.rabbitmq.listener.simple.retry.max-interval=300000

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Logs
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.org.springframework.cloud.openfeign.support=DEBUG
logging.level.feign=DEBUG