services:

  mysql:
    image: mysql:8.0
    container_name: room-reservation-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306" #host/container
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - room-reservation-net

  server-ms:
    build: ./server-ms
    container_name: server-ms
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - room-reservation-net

  config-server-ms:
    build: ./config-server-ms
    container_name: config-server-ms
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - room-reservation-net

  user-ms:
    build: ./user-ms
    container_name: user-ms
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      server-ms:
        condition: service_started
      config-server-ms:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server-ms:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-ms:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_ms?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-900000}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - "8081:8081"
    networks:
      - room-reservation-net

  room-ms:
    build: ./room-ms
    container_name: room-ms
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      server-ms:
        condition: service_started
      config-server-ms:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server-ms:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-ms:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/room_ms?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-900000}
    ports:
      - "8082:8082"
    networks:
      - room-reservation-net

  booking-ms:
    build: ./booking-ms
    container_name: booking-ms
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      server-ms:
        condition: service_started
      config-server-ms:
        condition: service_started
      user-ms:
        condition: service_started
      room-ms:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server-ms:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-ms:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booking_ms?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-900000}
    ports:
      - "8083:8083"
    networks:
      - room-reservation-net

  gateway-ms:
    build: ./gateway-ms
    container_name: gateway-ms
    restart: unless-stopped
    depends_on:
      server-ms:
        condition: service_started
      user-ms:
        condition: service_started
      room-ms:
        condition: service_started
      booking-ms:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-ms:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - room-reservation-net

volumes:
  mysql_data:

networks:
  room-reservation-net:
    driver: bridge
