<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>br.com.jhohannesfreitas</groupId>
    <artifactId>room-reservation-api-microservice</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>user-ms</module>
        <module>room-ms</module>
        <module>booking-ms</module>
        <module>gateway-ms</module>
        <module>server-ms</module>
        <module>config-server-ms</module>
    </modules>
</project>
